# Generated by Django 6.0.6 on 2026-06-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='会话')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=100, verbose_name='名称(中文)')),
                ('name_en', models.CharField(max_length=100, verbose_name='名称(英文)')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='分类图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='公司')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('product', models.CharField(blank=True, max_length=200, verbose_name='产品')),
                ('message', models.TextField(verbose_name='留言')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '询盘',
                'verbose_name_plural': '询盘',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='联系人')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='公司')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_zh', models.CharField(max_length=500, verbose_name='地址(中文)')),
                ('address_en', models.CharField(blank=True, max_length=500, verbose_name='地址(英文)')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('country', models.CharField(default='China', max_length=100, verbose_name='国家')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='邮编')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shop.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='联系人')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('shipping_address', models.TextField(verbose_name='收货地址')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('processing', '处理中'), ('shipped', '已发货'), ('delivered', '已签收'), ('cancelled', '已取消')], default='paid', max_length=20, verbose_name='状态')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总额')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=200, verbose_name='名称(中文)')),
                ('name_en', models.CharField(max_length=200, verbose_name='名称(英文)')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='主图')),
                ('specs_zh', models.TextField(blank=True, verbose_name='规格(中文)')),
                ('specs_en', models.TextField(blank=True, verbose_name='规格(英文)')),
                ('desc_zh', models.TextField(blank=True, verbose_name='描述(中文)')),
                ('desc_en', models.TextField(blank=True, verbose_name='描述(英文)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('is_featured', models.BooleanField(default=False, verbose_name='精选')),
                ('is_active', models.BooleanField(default=True, verbose_name='上架')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='购物车')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='图片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='shop_produc_slug_76971b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='shop_produc_is_feat_a70478_idx'),
        ),
    ]
